---
title: "Exp. 2 Analysis: 2AFC, adults vs. children"
author: "George"
date: Sys.Date()
output: html_document
---

```{r libraries}
knitr::opts_chunk$set(echo = TRUE)

require(here)
require(tidyverse)
require(tidyboot)
```



```{r load-model-data, include=F}
mdat <- read_csv("agent-data/curiodrop-model-8-23-20.csv")

names(mdat)
mdat <- mdat %>% mutate(
    train_stage = cut_number(model_train_steps, 2),
    chose_target = ifelse(choice==target, 1, 0)
  ) 
  
mdat %>% group_by(drop, target, train_stage) %>% # alt, 
  summarize(chose_target=mean(chose_target), n=n()) %>%
  ggplot(aes(x=train_stage, y=chose_target, group=target, color=target)) + 
  facet_wrap(.~ drop) + 
  geom_point(aes(size=n)) + geom_line() + theme_bw() + ylim(0,1)

mdat %>% distinct(drop, target, alt)
```


```{r load-human-data, include=FALSE}
raw = read.csv2("exp2-mturk-data/MturkAdultDrop-Data-Combined.csv", sep=',', header=F, stringsAsFactors = F)
# row 1 is empty, row 2 should be header
d = raw[4:nrow(raw),]
names(d) = raw[2,]
d[,"NA"] = NULL
# duplicate column names
#names(d)[13]
#names(d)[21]

# "Why did you make that choice?"
explanations = d %>% select(Q42, Q43) # should also select relevant trials

# Q38-Q41 = which toy did you just drop? (catch trials)
#d = d %>% select(-Q38, -Q39, -Q40, -Q41, -Q42, -Q43) # duplicate column names
d$Q11 = NULL
d$Q38 = NULL
d$Q39 = NULL
d$Q40 = NULL
d$Q41 = NULL
d$Q42 = NULL
d$Q43 = NULL
d$`Random ID` = NULL
d$`Duration (in seconds)` = "Duration"
#write.csv(d, file="exp2_cleaned.csv")
```

```{r}
rawch <- read_csv("human-data/DevoDrop_data_raw - Combined.csv") # children data
rawch[which(is.na(rawch$Exclude)),]$Exclude = 'N'

cd <- rawch %>% filter(Exclude!="Y") %>% 
  dplyr::select(-Version, -Torus0, -Exclude, -Qual1, -Qual2, -Notes)

# make long
#cdl <- cd %>% pivot_longer()

# first 10 columns are

for(i in 3:ncol(cd)) {
  tt = table(cd[,i])
  bt = binom.test(tt, p=.5, alternative="two.sided")
  cat(names(cd)[i], ' ', sum(tt), ' p=', round(bt$p.value,3))
  print(round(tt / sum(tt), 2))
}


```


```{r}
hist(cd$Age)
```

```{r}

```

